server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://47.99.145.139:3306/ANXING?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com:
      anxing:
        anxingservice:
          mapper: debug
